language: python

sudo: false

branches:
  only:
    - master
env:
  global:
    - LUAROCKS=2.3.0
    - TORCH_SERVER=https://raw.githubusercontent.com/torch/rocks/master/
  matrix:
    - LUA="lua 5.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks --from=$TORCH_SERVER install torch
  - luarocks make torch-travis-example-scm-0.rockspec CFLAGS="-O2 -fPIC -fprofile-arcs" LIBFLAG="-shared"

script:
  - lua tests/my_test_file.lua

after_success:
  - echo "Tests passed"

notifications:
  email:
    on_success: change
    on_failure: always