language: python

sudo: false

branches:
  only:
    - master
cache:
  directories:
  - torch

env:
  global:
    - TORCH_SERVER=https://raw.githubusercontent.com/torch/rocks/master/
  matrix:
    - LUA="LUA51"
    - LUA="LUA52"
    - LUA="LUA53"
    - LUA="LUAJIT20"
    - LUA="LUAJIT21"

before_install:
  - curl -s https://raw.githubusercontent.com/torch/distro/master/install-deps | bash
  - if [[ -f torch ]]; then git clone https://github.com/torch/distro.git torch --recursive ; fi
  - cp torch torch_$LUA
  - cd torch_$LUA
  - TORCH_LUA_VERSION=$LUA ./install.sh

install:
  - luarocks --from=$TORCH_SERVER install torch
  - luarocks make torch-travis-example-scm-0.rockspec CFLAGS="-O2 -fPIC -fprofile-arcs -ftest-coverage" LIBFLAG="-shared --coverage"

script:
  - luarocks install luacov
  - lua -lluacov tests/my_test_file.lua
  - luacov -c .luacov

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
